### ISSUE TITLE
Definição de requisitos

### ISSUE THREAD

**Issue by RubenCosta96** [RubenCosta96/repo_M01#12]
**Descrição**

Definição de requisitos

**Historias**
- [x] Modelo de casos de uso (CdU) de cada componente
- [x] Regras de negócio
- [x] Requisitos não funcionais
- [x] Pressupostos e restrições
